### ISSUE TITLE
Falling out of world at spawn

### ISSUE THREAD

**Issue by HoldfastFamily** [NeunEinser/bingo#107]
When loading new game, character spawns in air and falls out of world. Continues to happen after respawning. Have uninstalled and retried several times.

![2022-01-05_22 08 51](https://user-images.githubusercontent.com/94339637/148323276-62b099a8-94e3-4df5-90f9-0702d5697f88.png)

Not able to use lobby command ("unknown scoreboard objective")

**Comment by NeunEinser** [comment]
Since you closed this yourself, I assume you already solved it, but here are the two things that can cause this:

1. You are in the wrong Minecraft version. 1.16.5 is the correct version for all 5.0 versions.
2. You downloaded master. Make sure to always download the latest release from [the releases page](https://github.com/NeunEinser/bingo/releases) which is currently [Bingo 5.0-pre1](https://github.com/NeunEinser/bingo/releases/tag/5.0-pre1)
