### ISSUE TITLE
Stuck in Lobby

### ISSUE THREAD

**Issue by Aldebarr** [NeunEinser/bingo#143]
I have one friend that never leaves the lobby when a new game is started. 
I will take any suggestions on how to resolve this.

*it is worth mentioning that I have about half a dozen other people and none of them have this issue, only the one person. 
This person is in the correct version and has the resource pack enabled

**Comment by NeunEinser** [comment]
Hey, 

thanks for letting me know. I thought this would not happen anymore.

Which version of the map are you using?
And how did that player leave the resource pack check room? Did he leave the usual way by clicking the chat message, or were they somehow teleported in a different way?

**Comment by Aldebarr** [comment]
would have to double check, but pretty sure we are on 5.0 pre1
And now that you mention it, yes, he was teleported from the check room- had totally forgot about that

**Comment by NeunEinser** [comment]
They were teleported, as in teleported manually?

Yeah, that's not supported, everyone needs to go through the rp check properly, otherwise the player is not setup properly. I should probably prevent manual teleporting, to prevent issues like this.

I would recommend updating to the latest version (currently on 5.0 Release Candidate 3).

To fix the issue with the player, since they never did the rp check properly, they should still see the chat message when they join. Can you tell them to go through the instructions from the message? This should fix the issue.

**Comment by Aldebarr** [comment]
Thank you for the quick reply, appreciate you!

**Comment by NeunEinser** [comment]
This was fixed in 5.0.1 in 24b88fdae6558eb181e87e88d8578291f6c1b44e
