### ISSUE TITLE
Glitchy audio due to high coordinates

### ISSUE THREAD

**Issue by haz429** [NeunEinser/bingo#145]
Hi there,

Due to the fact that games are played at very high coordinates, the audio sounds "glitchy" and I believe this is due to issue [MC-191170](https://bugs.mojang.com/browse/MC-191170). This is especially noticable around mobs, as the position of their sound changes with even the slightest of movements, but personally makes playing the map difficult most of the time.

I don't know if there's a fix to this besides lowering the distance away from the origin the game is played, but thought I would mention it anyway. 

Thanks.

**Comment by NeunEinser** [comment]
As I understand the report, this should just offset the origin of sounds by a small amount, so something directly in front of you might make a sound that comes from the right side, since the game might have offset the origin by e.g. 1 block, so it's not in front anymore.

In 1.16, there is in general no way to distinguish whether something is above or below you. In 1.19 there is a way to toggle on a system that simulates full 3D audio in a better way.

So the question is what is it exactly you are struggeling with - and would it be fixed by moving closer to origin? I'm also unsure until which boundary MC-191170 applies, moving stuff closer to origin also automatically means you are more likely to spawn somewhere close to a previous spawn location, but it is certainly something that could be changed to some degree.

**Comment by purple512** [comment]
Hi, I was going to file a bug about this this problem but found the existing issue so I'll leave a comment instead.

The audio in 1.19.4 is driving me crazy. It's not just mobs, it's every sound. I created a test clip that uses the footstep sounds on podzol to demonstrate:

[Here is the link to the clip on Youtube (I don't know how to embed a video in a comment)](https://www.youtube.com/watch?v=Oihvd2r6JHs).

The first part of this clip is walking around in Fetchr 5.1 beta3. The second is walking on the same kind of terrain in a stock world.

You may have to wear headphones to hear it, but the footsteps in the first half are all over the place. Sometimes they come in on the left, or the right; they should always be in the center. And in general, I find all the sounds to have some kind of "swimmy" attribute to their tone. In the second clip all the sounds are localized to the center and sound like they should. It might be a bit subtle but anyone used to the Minecraft sounds should pick up on it immediately.

This is a vanilla 1.19.4 instance, no mods.

Undoubtedly this is an upstream Minecraft issue and not something that can be solved by Fetchr. But perhaps as with the item entity being thrown in random directions bug thing, this might shine some light on an existing issue?

Thank you for your time.

**Comment by purple512** [comment]
I read through the Mojang bug report linked above and one of the suggested things was adding `stereo-mode = headphones` to `alsoft.ini`. I tried that and it did absolutely nothing, which was pretty much expected as this almost certainly is a floating point precision issue which has nothing to do with OpenAL.

**Comment by NeunEinser** [comment]
The block drop issue was actually fixed by Mojang, there may have been ways to work around that one as well, but in case of sounds there is nothing that can be done from my side, sadly

**Comment by JPenuchot** [comment]
Not 100% sure but I think the high coordinates mess with graphics too. I've had glitches like chunks becoming invisible at certain camera angles, shadow offset, and a friend reported to me that he saw hitboxes displayed in black instead of white when playing Fetchr. I don't have any of these on my regular SMP depite using the same instance/client.

**Comment by NeunEinser** [comment]
Closing this as there really isn't a way for me to fix this, without Mojang to allow dynamically generating dimensions or deleting chunks from a datapack.
