### ISSUE TITLE
Block drops spawn at the wrong position

### ISSUE THREAD

**Issue by williamhaecom** [NeunEinser/bingo#161]
I am not sure if this is a Fetchr bug, a 1.19.3 bug, or a misconfiguration on my part.  I am not able to reproduce this issue on a non-fetchr 1.19.3 server.

When breaking blocks, the drops are sometimes flung a great distance away.  

I tried reducing the server side and client side render distance to 10 to see if it is a performance issue, but there was no change.  The server java memory is set to 1024M/4096M.

**Comment by UnlucksMcGee** [comment]
It's a bug that got introduced in 1.17 and is fixed in 1.19.4. At high coordinates, the position at which an item pops out gets offset by as much as 2 blocks causing it to fling a great distance.
https://bugs.mojang.com/browse/MC-229293

slicedlime brought it up to the dev team that this bug would become a lot more noticeable due to this bingo, and thus it was fixed for 1.19.4 😁

**Comment by NeunEinser** [comment]
Leaving open until Fetchr is running on 1.19.4
