### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by ski-freak** [NeunEinser/bingo#173]
Cool datapack! Here's some ideas after playing with it for a bit with friends:

- Allow custom item goals / weights (I might try digging through and changing it myself for not, but I don't know mcfunction and didnt find a text or json file with all the goals or anything, maybe you can point me to how to do this?)
- Advancements as goals? Could be nice as a secondary pool of goals to take from, as a toggleable option.
- Option for squares to be only taken by one team at a time, perhaps in this case you can either go for bingo or take more squares than the other team(s)? Not sure how this would work on such a big board, might never end in bingo, I like the more direct counterplay of being able to block though.
- Best 2 of 3 bingo. One of the things I noticed when playing is that everything is very early game, you almost never need to go to the nether, and even if items from further along in progression were included you would just end up avoiding them in choosing a line to go for bingo on. My idea is to have 3 boards, one for early game, a middle one, and a late game one, so the objectives in each single board can be consistent in difficulty while still having later game things. All of these boards would be much smaller, 3x3 or 4x4. In order to win the bingo match you need to complete 2 of the bingo boards, so you could finish the first and second, second and third, or first and third (more than your opponent). The best 2 out of 3 format would only work in 1v1 (or 1 team vs 1 team), for more than 2 teams it would need to just be a race to complete all three boards. I believe this concept of multiple smaller boards on top of allowing for more progression could also reduce the amount of decision paralysis of overwhelming options when you are new to the bingo, and work well with the blocking mentioned in the previous idea. This may also create a nice pacing to the game, with multiple discrete stages rather than one big thing waiting to happen, but this last bit is more of an abstract theory and I have no idea if that would be the case in practice.

I would honestly give it a try myself at adding some of these on my own, but I don't know where to begin as I am not a very good programmer, and as I mentioned don't know much of how mc datapacks work. Also how do you test this datapack, do you make a new world every time (I think the modrinth page mentioned not using it on an existing world)?

**Comment by NeunEinser** [comment]
- Items are registered in https://github.com/NeunEinser/bingo/blob/fa31b6f296358b0d599d684770504d6c74076bbd/datapack/data/fetchr/functions/init/fill_registries.mcfunction. You can edit those in place. There is also a way to create an expension pack, which is mostly relevant for if you wanted to distribute it.
However, note that both versions are experimental and you may encounter bugs when trying to change or add items.
- Since this would become harder and confusing to communicate, I want to stick to the simplistic approach of only requiring items. Most advancements can be reflected with a item in some way anyways.
- Items to be restricted to a single team is being tracked in #92.
- Best of 3, I guess I don't understand the problem you are trying to solve here. To me it seems more overwhelming and confusing having to deal with 3 separate boards. Besides, for a more difficult objective, you can already go for e.g. a Blackout, among other goals.
It would also be difficult to visualize, or at least I can't think of a good way to display that in the lobby or action bar.
- The advisory to create a new world is related to the datapack completely overriding the overworld with a void dimension, so you shouldn't use this pack in an existing world you care about, and there may be bugs using it on an existing world with terrain generated without the pack. For working on the pack, you can simply make changes and use `/reload`.


In the future, please try to keep it as one suggestion / question per issue, so that those can be kept track of individually.

**Comment by That-Ski-Freak** [comment]
Is blackout implemented in the datapack already?

**Comment by NeunEinser** [comment]
It's in the goals section of the post on the website you downloaded from (e.g. Modrinth)

**Comment by NeunEinser** [comment]
It's in the general information section of the post on Modrinth
