### ISSUE TITLE
Is the nether disabled?

### ISSUE THREAD

**Issue by ski-freak** [NeunEinser/bingo#175]
I went into creative and made a portal but it doesn't open, is the nether disabled in this datapack? Didn't see any info on this on the mod page. I was doing this because I wanted to make a nether bingo variant, but if there is no nether then I guess I can't.

**Comment by NeunEinser** [comment]
Nether is disabled due to technical limitations with custom dimensions - portals would not link properly back to the main world.

**Comment by That-Ski-Freak** [comment]
What part of the map is using custom dimentions? Also could it be possible to just teleport the player when they come back to the overworld, to the spawn location of that bingo possibly? Wouldn't be the same as vanilla but might be better than nothing.

**Comment by NeunEinser** [comment]
Sure, feel free to do that, it won't be merged into my release tho.

**Comment by That-Ski-Freak** [comment]
Ok, can you please point me to where in the code you disable the nether?

**Comment by NeunEinser** [comment]
Turns out it actually just doesn't work at all - you can't light a nether portal in a custom dimension in any case.
The nether is only disabled in the level.dat file, so if you use the datapack version, the nether does exist and you can go there with `execute in minecraft:nether run tp ~ ~ ~` or simply `/setblock ~ ~ ~ minecraft:nether_portal`

**Comment by That-Ski-Freak** [comment]
Oh, unfortunate
