### ISSUE TITLE
Game starts pregenerating and teleports automatically after tapping card sign

### ISSUE THREAD

**Issue by RillSoji** [NeunEinser/bingo#177]
About 3-5 seconds after tapping the Generate Random Card sign, the player's card interface and hud fade out and in twice then players are teleported to the pregen platform without tapping the Join Game sign. 

If this is intended behavior it would be nice to have that pregen start maybe 10 seconds later to give a chance to look at the card and pick a diff one if desired. 

If it's not intended behavior may I get an assist for fixing the issue? 

Tried it on both a vanilla server and fabric server. Client is clean and did try tapping the sign as OP and not OP. All with same results.

**Comment by UnlucksMcGee** [comment]
When the HUD fades out, that is an indication that the server is lagging a bit, which is common when the chunks are being pre-generated.

The experience you describe is less than ideal, so there might be some improvements that can be made.

But as a temporary workaround, in the bingo settings (on the left of the lobby), you can toggle the chunk pre-generation to only happen after you click join game sign, instead of after the card is generated.

**Comment by RillSoji** [comment]
Thank you!

**Comment by NeunEinser** [comment]
Pre-generation starts 5 seconds after picking a card (causing the first fade out on lower end devices - the first chunk is especially laggy to generate for some reason), the player is teleported after the first 9 chunks are generated after an arbitrary delay depending on server performance.

If you do not like the card or spawnpoint the only option currently is to leave the game and generate a new one.

I don't really like the idea of doubling the delay, as players who just want to play any card would have to wait longer, and it doesn't really solve the problem, as you might still not be fast enough.

Two ideas:
1. Provide an option to not automatically join the game in SP
  - When active, essentially the same as 5.0 with an extra sign click to join the skybox and then start the game
  - Don't like it too much, as I like the idea of studying the card while studying the spawn point
3. Add generation controls to the skybox (e.g. encase the skybox lobby with black concrete until the new spawnpoint is ready to be revealed)
  - This has the benefit that you could also quickly reject a card when the spawn looks bad, or decide to play a card you otherwise wouldn't based on the spawn
  - Probably the experience of being teleported to a secondary generated spawn should be smoother, as there won't be any dimension switch
  - More complexity in implementation

> But as a temporary workaround, in the bingo settings (on the left of the lobby), you can toggle the chunk pre-generation to only happen after you click join game sign, instead of after the card is generated.

This option has been removed since the first 5.1 beta, and more extensive settings will be provided at a later time when the pre-gen rework is done.

**Comment by NeunEinser** [comment]
Added "generate random card" sign to the skybox for next release.
