### ISSUE TITLE
Bingo card not updated (team colors)

### ISSUE THREAD

**Issue by Aurelien30000** [NeunEinser/bingo#189]
Due to the following commit, the bingo card is not updated when an item is obtained by a team. I haven't found the origin of the issue but I hope it will help you :)

https://github.com/NeunEinser/bingo/commit/0a29733bbef6071729f5b0c0d8a4375e36ba2255

**To replicate the issue, you just need a basic setup and to run a basic game, no blind/lockout game needed.**

Thanks!

**Comment by NeunEinser** [comment]
Hmm, pretty sure this is something on your end. I tested again on current dev branch and everything appears to be working(item being marked with team color and appearing with darker shade).

The commit you mentioned moved the files related to updating the card to a different directory, possibly there was some sort of merge conflict you missed / resolved wrongly when updating your fork?

**Comment by NeunEinser** [comment]
Oh I think I know.

The function is called by the item detection command blocks in the lobby. Since the file location changed, the command block in the lobby running the function was updated to call the function at the new location.

Just delete everything in your world folder except level.dat and the datapacks directory, so it re-generates the lobby with the new structure.

**Comment by Aurelien30000** [comment]
Oh! You are right, I apologize for the issue, thanks a lot for the help :D

**Comment by Aurelien30000** [comment]
Oh! You are right, I apologize for the issue, thanks a lot for the help :D
