### ISSUE TITLE
TPS dropping like crazy because fetcher keeps on detecting items

### ISSUE THREAD

**Issue by heerxingen** [NeunEinser/bingo#211]
My server runs fine with more than 10GB of RAM
but when I added fetcher suddenly stuff stopped working well
When I gave my self op permission, this is what I saw
![W1A 1@MFXLCGECHE8{R20LT](https://github.com/NeunEinser/bingo/assets/102276349/a37692f6-5409-4cf1-923b-1cc97d69783a)
Fetcher keeps on detecting what items are in my backpack and it made my tps drop like crazy, and when I gave myself op I can't even send a message because everything flashes by since my message box was flodded with fetcher's detecting updates.
I mean, why do you have to update like every 0.05 seconds???
I hope you'll fix this soon since I can't even find the datapack in my server now LOL
(Also the Chinese translation **isn't** complete although it's _**supposed to be**_, but I'll translate the untranslated parts for you guys)

**Comment by Steven-Jim** [comment]
and another thing, as soon as I entered the /function fetchr:game/end command, the tps became normal like this
<img width="576" alt="image" src="https://github.com/NeunEinser/bingo/assets/102276349/9fb5141e-d0a9-4cdf-a750-9b4d694d0379">

**Comment by Steven-Jim** [comment]
Oh and my version of fecher is 5.1.1

**Comment by NeunEinser** [comment]
This looks like a mid issue. Command block output is disabled in the map.

The recommended setup on the server side is Fabric with Lithium for best performance. You can also run vanilla.

Note that especially Paper/Spigot (even with no plug-ins installed) messes with datapacks and breaks things in subtle ways.

Client-side mods do not matter when joining a server, but they could be problematic when playing single player.

**Comment by Steven-Jim** [comment]
oh ok my server runs purpur and I know it's a fork of paper. I'll just run the setup you've recommeded
and I'll also enable command blocks(I keep on forgetting)
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/5/2023 03:54 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [NeunEinser/bingo] TPS dropping like crazy because fetcher keeps on detecting items (Issue #211) |

This looks like a mid issue. Command block output is disabled in the map.

The recommended setup on the server side is Fabric with Lithium for best performance. You can also run vanilla.

Note that especially Paper/Spigot (even with no plug-ins installed) messes with datapacks and breaks things in subtle ways.

Client-side mods do not matter when joining a server, but they could be problematic when playing single player.

**Comment by Steven-Jim** [comment]
Ohno I can't remember the password to my server LOL
I'll try fetcher on my friend's realm.

**Comment by NeunEinser** [comment]
Last time I checked, realms did not support worldgen datapacks.

They did a recent change were experimental features are available on realms now, but not sure if that also allows for worldgen packs now.

**Comment by Steven-Jim** [comment]
Ohno
so that's why I spent yesterday afternoon trying and trying to load Fetchr onto my friend's Realm LOL
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/10/2023 01:04 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [NeunEinser/bingo] TPS dropping like crazy because fetcher keeps on detecting items (Issue #211) |

Last time I checked, realms did not support worldgen datapacks.

They did a recent change were experimental features are available on realms now, but not sure if that also allows for worldgen packs now.
