### ISSUE TITLE
Incorrect skybox floor rendering in 1.21.0 - 1.21.1

### ISSUE THREAD

**Issue by davepusey** [NeunEinser/bingo#242]
Testing in 5.1.4-beta1 on 1.21.0 and 1.21.2-rc1

1.21.0 is affected, 1.21.2-rc1 is not.

I thought this might be what d2a2ebfbc752ba709c2c123cfd20c43390ccf3f0 fixed but that was from before beta1 was released, so perhaps not?

![2024-10-19_15 41 13](https://github.com/user-attachments/assets/f012ccc6-d5e4-4188-a61b-fd9eea1093ab)

**Comment by NeunEinser** [comment]
The commit you mentioned was indeed fixing this issue, but I didn't check the earlier versions. Looks like I have to go back to custom model override which is unfortunate.

It looks like the `item_model` component does only exist since 1.21.2, which I didn't expect (and the wiki doesn't list it properly which I'm fixing now :D)
