### ISSUE TITLE
Players can destroy lobby

### ISSUE THREAD

**Issue by opl-** [NeunEinser/bingo#48]
Players in lobby aren't in adventure mode, allowing them to decimate everything. This makes it difficult to host servers without someone to oversee them.

**Comment by NeunEinser** [comment]
It's meant to be a nod to oldscool bingo where people liked to place trophies and decorate the lobby as they pleased.
I do intend to make a lobby gamemode setting for servers though and it is certainly nice to have an issue to track this. I am going to categorize this as an enhancement rather than a bug though ;)
