### ISSUE TITLE
Adding more newlines in preferences menu

### ISSUE THREAD

**Issue by UnlucksMcGee** [NeunEinser/bingo#78]
I think the preferences menu would look cleaner if more newlines were added in between the sections.

As seen in this pic, it can be confusing for the player if they can still see the previous section (shown in red).
![image](https://user-images.githubusercontent.com/74118470/139864083-ac32c5e9-98b1-48d3-9399-b298e6f7d12b.png)

**Comment by NeunEinser** [comment]
So, it is intentional that the previous menu page is not off screen entirely.
The reasoning behind that is that I want people to still see chat messages in case they came in right as they clicked, or right before.

Personally, I felt the gap is sufficient, especially when you see the new stuff appear.
But what would you think the gap should be?

Current is 3 line feeds.

4:
![grafik](https://user-images.githubusercontent.com/12124394/139875071-138b90db-a5e2-41b5-b665-483c7d55c669.png)

5:
![grafik](https://user-images.githubusercontent.com/12124394/139875258-b225ecc3-d5dc-4691-9efe-af8eddc40125.png)

6:
![grafik](https://user-images.githubusercontent.com/12124394/139875447-0e475779-74d0-41d2-be10-931f0eeff860.png)

**Comment by UnlucksMcGee** [comment]
Ah, that is a valid reason, to not miss chat messages.

Perhaps then the default is fine, otherwise maybe 5 line-feeds? (only because 5 is a nice number :smile:)
