### ISSUE TITLE
Bingo card position interface ideas

### ISSUE THREAD

**Issue by UnlucksMcGee** [NeunEinser/bingo#79]
These are my ideas for the bingo card positioning interface. If you approve these suggestions, then I could maybe work on a pull request with the changes.

### 1. Simplify adjustment interface
The current Bingo card adjustment menu looks like this:
![image](https://user-images.githubusercontent.com/74118470/139865078-ea3e4118-aac6-4409-928a-b150dba45a56.png)

My suggestion is to simplify it, and only have "shift left", "reset" and "shift right" buttons.
![image](https://user-images.githubusercontent.com/74118470/139866768-98319886-2354-444e-8ba4-32bee1e580be.png)

This makes the interface clean (don't need to add a ton of options for all the positions), makes it more intuitive for the user.

### 2. Change card_pos values
The `bingo.card_pos` scoreboard can be adjusted such that the card positions are ordered in terms of their screen position from left to right. (This makes the above interface suggestion simpler to implement.)

e.g. The default position can be `0`, then when you click left, it decrements the score to `-1` which would represent the "left edge (gui 4)" position, followed by "left edge (gui 3)" and so on.

e.g. If you click right, it increments the score to `1` which is "next to hotbar (right)", then `2` would represent "next to attack indicator" and so on.

### 3. Add new (or replace default) card position
I suggest adding this additional card position (or maybe replacing the current default with it?).
This new position has a gap between the hotbar and the bingo card making it look less cramped against the hotbar/time.
The width of the gap is equal to the space between the hotbar and offhand slot to keep it symmetrical.

The current default is shown in red, with my suggestion in green:
![image](https://user-images.githubusercontent.com/74118470/139872695-3a6489c2-fcd6-41e8-808b-9338dec1fde2.png)

**Comment by NeunEinser** [comment]
> which would represent the "left edge (gui 4)" position, followed by "left edge (gui 3)" and so on.

Left/right edge is disabled because it doesn't work properly -- I need information about screen resolution as well, that what you saw in the function foolishly assumed it's only defendant on GUI size and tested with my 1080p monitor. There are even GUI sizes that only become available with a higher res monitor and technically there is no limit on GUI size either.

And yeah, I still think the best solution is to incorporate the card into the custom hud system, as this would also allow to set other components in spots which are currently only available for the card.

I am aware that the current interface for the card isn't ideal right now, but it's the best option without major changes for now (minimum required change is to prompt the player for gui size, screen resolution and attack indicator in a nice non-annoying and skipable way).

**Comment by NeunEinser** [comment]
I created #85 now for refactoring the card as HUD component.
Having other components in that slot requires a margin anyways, so this is also included in there.

Thus this issue is redundant now.
