### ISSUE TITLE
More options for compass or icon that's easier to read

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#84]
The compass icon has a bunch of problems, namely:

- Depending on GUI size, the compass needle can become invisible for certain rotations
- The compass is not an item in commonly used in modern times, so players can be confused about how to read it correctly

To fix that, there should either be an OPtion to directly display N/E/S/W, or even better the icon could change.
If this is doable with the available pixels, the icon could be rotating letters N/E/S/W so that you can see for example see in the icon you are midway between N and E.

**Comment by Kri5t0fK** [comment]
For the record - `bingo compass`' purpose is to always point towards North?

**Comment by NeunEinser** [comment]
Yes.

**Comment by Kri5t0fK** [comment]
About the icon with rotating letters, here is a proof of concept.
![image](https://user-images.githubusercontent.com/53398204/153761472-8b60feae-35d7-4358-adb4-f7057c0c17b6.png)
Issues:
- colors of letters
- color blindness #109 - pixellated letters may be hard to read, 
  that's why there should also be direct display of N/E/S/W next to icon

**Comment by NeunEinser** [comment]
Hmm, with the idea of using rotating letters I was mostly thinking of completely replacing the compass (not trying to encoperate the compass in the icon at all) and only have the letters in white font.

**Comment by Kri5t0fK** [comment]
I was going to ask about that - _make custom `bingo compass` texture_

Yeah, it'll be more easily doable than putting it in compass texture, cause of more available pixels.

Also... we can make 2 _bingo compasses_ - 1st as it is; 2nd with rotating letters - so people can choose which suits them better

**Comment by NeunEinser** [comment]
Hmm, I think I see objectively very little advantage of the MC icon if we can make rotating letters work.
If people complain or we find during design that there is an advantage in the old icon, we can always make an option later.

**Comment by Kri5t0fK** [comment]
Here is my idea - compass-360 (sliding letters, like compass HUD on top in many games)
![image](https://user-images.githubusercontent.com/53398204/153971210-9718a46e-cfa3-45a8-a537-cae6d22d6917.png)
Example from other game:
![image](https://user-images.githubusercontent.com/53398204/153971672-dbd55ba4-7bf9-4051-a296-7b565c9dd2e1.png)
Letters should probably be upscaled to bigger scale, so shadow is more consistent with width. But overall it's functional

> For **quick test** of feel - take image below and replace [`compass.png`](https://github.com/NeunEinser/bingo/blob/c8e309b98fc33dc671385dc00bd06afd7e90b175/assets/bingo/textures/font/compass.png) with it
> ![compass](https://user-images.githubusercontent.com/53398204/153971222-f0b49acd-f57d-4e0c-9a39-fbec95f20d77.png)

**Comment by NeunEinser** [comment]
I like that general idea.
I messed a bit with it as well, I feel like the indicator is not visible enough. Here I tried adding a solid line through it
![grafik](https://user-images.githubusercontent.com/12124394/154150374-142d1647-2132-47ad-9a03-e55ed7a62f02.png)

I feel like the red is still not optimal though, especially considering color deficiencies.
Black is not very visible if it's in between the letters though.
![grafik](https://user-images.githubusercontent.com/12124394/154151400-4b19e4cb-1659-4a52-a305-32df19365d6e.png)

I also tried "inverting" the original color (white in general and black when there is something on the other layer), but that seems like the worst one so far
![grafik](https://user-images.githubusercontent.com/12124394/154153204-abeee901-7572-4c4e-91f1-49e5d1ad355c.png)

Since this should be the most easy to edit, this is that last iteration: [compass_letters.zip](https://github.com/NeunEinser/bingo/files/8074904/compass_letters.zip)
Not sure exactly, it's kinda hard to make the indicator good with a pixelated style and a small icon like this.

**Comment by Kri5t0fK** [comment]
I think `red` is the best choice _for now_ - it's neither white nor black, so no matter the color deficiency type, it should be a 3rd color.

**Comment by UnlucksMcGee** [comment]
I wrote a small python script that can take in images to generate the `compass.png` font file. It's a bit messy but is functional. The script allowed me to experiment with a couple of different designs pretty quickly.

Requirements:
- `static.png` should be the same height as `scroll.png`
- `scroll.png` should be at least 32 pixels wide if scrolling by 1 pixel each time.

```python
import numpy as np
from PIL import Image


def nice_blend(img_above, overlay):
    # From: https://stackoverflow.com/a/64929862
    # Note: img_above is placed above the overlay
    srcRGB = img_above[..., :3]
    dstRGB = overlay[..., :3]
    # Extract the alpha channels and normalise to range 0..1
    srcA = img_above[..., 3] / 255.0
    dstA = overlay[..., 3] / 255.0
    # Work out resultant alpha channel
    outA = srcA + dstA * (1 - srcA)
    # Work out resultant RGB
    outRGB = (
        srcRGB * srcA[..., np.newaxis]
        + dstRGB * dstA[..., np.newaxis] * (1 - srcA[..., np.newaxis])
    ) / outA[..., np.newaxis]
    # Merge RGB and alpha (scaled back up to 0..255) back into single image
    outRGBA = np.dstack((outRGB, outA * 255)).astype(np.uint8)
    return outRGBA


if __name__ == "__main__":
    # Number of pixels to scroll each time
    N_PIXEL_SCROLL = 1
    # How many pixels to offset to center 'S'. Play with the value until it works
    HORIZONTAL_OFFSET = 4

    scroll_image = np.array(Image.open("scroll.png"), np.uint8)
    static_image = np.array(Image.open("static.png"), np.uint8)

    WINDOW_WIDTH = static_image.shape[1]
    WINDOW_HEIGHT = static_image.shape[0]
    OUTPUT_IMAGE_WIDTH = WINDOW_WIDTH * 16
    OUTPUT_IMAGE_HEIGHT = WINDOW_HEIGHT * 10
    SECOND_ROW_Y_START = WINDOW_HEIGHT * 5

    output_image = np.zeros((OUTPUT_IMAGE_HEIGHT, OUTPUT_IMAGE_WIDTH, 4), np.uint8)

    # Do an initial scroll of the image so that it lines up over 'S' South
    scrolled_image = np.roll(scroll_image, HORIZONTAL_OFFSET, axis=1)

    for row in range(2):
        for column in range(16):
            # Scroll the image along by N pixel(s)
            scrolled_image = np.roll(scrolled_image, N_PIXEL_SCROLL, axis=1)

            # Crop the first section of the scrolled image
            current_image = scrolled_image[:, :WINDOW_WIDTH]
            # Add the static image on top of it, blending them correctly
            current_image = nice_blend(static_image, current_image)

            # Add to the output image
            output_image[
                row * SECOND_ROW_Y_START : row * SECOND_ROW_Y_START + WINDOW_HEIGHT,
                column * WINDOW_WIDTH : column * WINDOW_WIDTH + WINDOW_WIDTH,
            ] = current_image

    # Save image
    img = Image.fromarray(output_image.astype(np.uint8))
    img.save("compass.png")

        for column in range(16):
            # Scroll the image along by N pixel(s)
            scrolled_image = np.roll(scrolled_image, N_PIXEL_SCROLL, axis=1)

            # Crop the first section of the scrolled image
            current_image = scrolled_image[:, :INDIVIDUAL_WIDTH]
            # Add the static image on top of it, blending them correctly
            current_image = nice_blend(static_image, current_image)

            # Add to the output image
            output_image[
                row * SECOND_ROW_Y_START : row * SECOND_ROW_Y_START + INDIVIDUAL_HEIGHT,
                column * INDIVIDUAL_WIDTH : column * INDIVIDUAL_WIDTH
                + INDIVIDUAL_WIDTH,
            ] = current_image

    # Save image
    img = Image.fromarray(output_image.astype(np.uint8))
    img.save("compass.png")
```

After some experimenting, I settled on two main options.
### Option 1
Given `scroll.png` image: ![scroll](https://user-images.githubusercontent.com/74118470/168472756-d18e2003-7ac0-4b45-9c87-f76c9600f5b0.png) and `static.png` image: ![static](https://user-images.githubusercontent.com/74118470/168472775-deb88dfb-db47-41ea-a51c-7896979b5975.png)

The script produced: 
![compass](https://user-images.githubusercontent.com/74118470/168472786-8359a792-5386-4b42-a06e-1de9f402d304.png)

![image](https://user-images.githubusercontent.com/74118470/168474715-c6a4fa05-4835-431c-b488-5988277a3446.png) ![image](https://user-images.githubusercontent.com/74118470/168474748-43647509-47fb-46fe-ab88-19f4a870abfe.png)

The width of the `static.png` image determines the width of the "view window" for the compass. After some experimenting, I preferred a width of 15 pixels.
For the `scroll.png` image, I wanted to reduce the height of it as much as possible, to ensure the letters are clear and large. Thus I only kept a single indicator at the bottom. I also found that having the letters aligned to the top (with the indicator below) looked the best visually, as it looks more aligned with the other HUD text beside it, otherwise, it is sunken down a bit.

For the static indicator, I decided to omit the evenly-spaced dots marking the major angles around, as it cluttered the image a bit and I don't think a player is too concerned over those as they can always align themselves using the blocks surrounding them. For the red indicator itself, I made it a bit fatter/wider so that it is more visible.

### Option 2
Another alternative I tried that is more in line with the last iteration you made is the vertical red line (with some opacity).
I reduced the height of the letters further and added a text-shadow similar to the rest of the HUD. This results in the text looking visually the same as the rest of the HUD (which I quite like). I was debating keeping a background shadow since now the text has its own shadow. But I decided on keeping the whole background dark so that this HUD element is visually distinct from the text beside it, otherwise, it can clash a bit and cause confusion as to where the compass element ends and where the coordinates element begins.

Given `scroll.png` image: ![scroll3](https://user-images.githubusercontent.com/74118470/168474455-a4daf50e-3b23-48e5-a10c-ee6f896fc64e.png) and `static.png` image: ![static3](https://user-images.githubusercontent.com/74118470/168474466-70e01d4d-2660-41a2-9142-d5275adbe665.png)

The script produced:
![compass](https://user-images.githubusercontent.com/74118470/168474524-addaae4f-933c-4e52-aad5-ab94d2fba7da.png)

![image](https://user-images.githubusercontent.com/74118470/168474661-35c270c3-50ff-4f48-baf4-ce58ab777405.png) ![image](https://user-images.githubusercontent.com/74118470/168474809-3909621c-e184-4338-8a72-fb2c2129dffb.png)



These are of course just suggestions, that might need some tweaking to be perfect. But the script is quite helpful to quickly iterate designs. With the "view window" being a different size to the original compass icon, it messes up the spacing of the text to the right, as well as the bingo card on the left. I assume this is something that can be fixed somewhere in the HUD code?

**Comment by UnlucksMcGee** [comment]
I also tried a more ambitious one, with a pixel scroll of 3. Although it is bordering on being just a static compass displaying the current direction, instead of a neat scrolling compass.

Given scroll.png image: ![scroll4](https://user-images.githubusercontent.com/74118470/168486622-9a469f6a-2fab-4dd2-adcc-6c7bc238f177.png) and static.png image: ![static3](https://user-images.githubusercontent.com/74118470/168486629-4b232b99-22d3-496a-8993-a995c34cf5f0.png)
The script produced:
![compass](https://user-images.githubusercontent.com/74118470/168486639-4197dd7b-d05a-4c21-8740-320a430c9ceb.png)

Here is a video showing how it looks. I think the 3 pixel scroll (necessary to have enough spacing for the minor cardinal directions) makes it too jumpy.

<video src='https://user-images.githubusercontent.com/74118470/168486672-536d83da-def4-41f2-9c3e-d5109a3889d5.mp4'/>

**Comment by NeunEinser** [comment]
I think I like both designs from your first comment. Not really sure which one I prefer, perhaps a video showcasing them would be good too.

I also think the 3rd one is too jumpy and I don't really like it.

... And I think in a later version I wanna look into displaying a wider compass at the top center using a bossbar, which then could use something similar to your third suggestion. But that's long term, for now just change the compass icon, and provide an option to switch between them.

**Comment by Kri5t0fK** [comment]
I also like both designs from @UnlucksMcGee's first comment (**Design 1** and **Design 2**)

Oh, interesting idea with big compass at the bossbar ;)
> _(...) compass at the top center using a bossbar (...)_ ~NeunEinser

**Comment by UnlucksMcGee** [comment]
I decided on design 2, as the text is then the same size as the rest of the HUD and it doesn't get distorted since design 1 gets shrunk to fit in place.

I thought that a triangle pointing up would be the best visual indicator:
![image](https://user-images.githubusercontent.com/74118470/172025418-55070ea3-480e-47cb-a37b-5f47c11759fc.png)

I experimented with how the red indicator overlays the NSWE letters since with this design there is no extra space below.
## Design 3 - Opaque
Here the red indicator just sits on top of the letters.

compass.png: 
![compass_opaque](https://user-images.githubusercontent.com/74118470/172025525-d89e2166-e6c8-4b66-a9b1-815903e07ae8.png)

Enlarged screenshot within GIMP for easier viewing here:
![image](https://user-images.githubusercontent.com/74118470/172025541-d352a8c1-6c9b-4ec9-aa07-8a797c3fd959.png)

Video:
<video src="https://user-images.githubusercontent.com/74118470/172025569-921d1236-b358-4ad2-97ed-0f6e714d2789.mp4"></video>


## Design 4 - Opacity
Here the red indicator sits on top of everything, except the white pixels of the letters. Instead, it is a slightly transparent red, so that the letters aren't fully obscured by the indicator.

compass.png: 
![compass_alpha](https://user-images.githubusercontent.com/74118470/172025696-d4aaf770-174b-4224-8945-451627eddfe3.png)

Enlarged screenshot within GIMP for easier viewing here:
![image](https://user-images.githubusercontent.com/74118470/172025705-64bc900e-3fb6-4db8-828f-d5cc835c1877.png)

Video:
<video src="https://user-images.githubusercontent.com/74118470/172025718-ad2899ca-a9d0-46bd-b7f4-d20a519ae11c.mp4"></video>
